version: '3.8'
services:

  lvis-db:
    image: postgres:16
    ports:
      - 5435:5432
    environment:
      POSTGRES_USER: jay
      POSTGRES_PASSWORD: jay123
    networks:
      - lvis-network
    restart: always
    volumes:
      - lvis-db-data:/var/lib/postgresql/data
      - ./init-db:/docker-entrypoint-initdb.d

networks:
  lvis-network:
    driver: bridge

volumes:
  lvis-db-data:
