version: '3.8'
services:

  system-db:
    image: postgres:16
    ports:
      - 5435:5432
    environment:
      NODE_ENV: development
      POSTGRES_USER: jay
      POSTGRES_PASSWORD: jay123
      POSTGRES_DB: lvis_system_db
    networks:
      - lvis-network
    restart: always

  warehouse-db:
    image: postgres:16
    ports:
      - 5437:5432
    environment:
      NODE_ENV: development
      POSTGRES_USER: jay
      POSTGRES_PASSWORD: jay123
      POSTGRES_DB: lvis_warehouse_db
    networks:
      - lvis-network
    restart: always

networks:
  lvis-network:
    driver: bridge
